### ISSUE TITLE
Error running namerd

### ISSUE THREAD

**Issue by gianrubio** [BuoyantIO/linkerd-examples#65]
I trying to run linkerd-examples for k8s but I can't run named. When namerctl start I got this error
```
$ kubectl logs -f namerd-sqpko namerd
-XX:+AggressiveOpts -XX:+CMSClassUnloadingEnabled -XX:CMSInitiatingOccupancyFraction=70 -XX:+CMSParallelRemarkEnabled -XX:+CMSScavengeBeforeRemark -XX:InitialHeapSize=33554432 -XX:MaxHeapSize=1073741824 -XX:MaxNewSize=134217728 -XX:MaxTenuringThreshold=6 -XX:OldPLABSize=16 -XX:+PrintCommandLineFlags -XX:+ScavengeBeforeFullGC -XX:-TieredCompilation -XX:+UseCMSInitiatingOccupancyOnly -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseStringDeduplication
Nov 22, 2016 10:36:30 AM com.twitter.finagle.http.HttpMuxer$$anonfun$4 apply
INFO: HttpMuxer[/admin/metrics.json] = com.twitter.finagle.stats.MetricsExporter(<function1>)
Nov 22, 2016 10:36:30 AM com.twitter.finagle.http.HttpMuxer$$anonfun$4 apply
INFO: HttpMuxer[/admin/per_host_metrics.json] = com.twitter.finagle.stats.HostMetricsExporter(<function1>)
I 1122 10:36:31.642 THREAD1: Finagle version 6.39.0 (rev=f49b26aa1a89cbaec5aa7ac956ae7f379b4a5d97) built at 20161011-165646
I 1122 10:36:32.160 THREAD1: Resolver[inet] = com.twitter.finagle.InetResolver(com.twitter.finagle.InetResolver@189f665)
I 1122 10:36:32.162 THREAD1: Resolver[flag] = com.twitter.server.FlagResolver(com.twitter.server.FlagResolver@c16548)
I 1122 10:36:32.163 THREAD1: Resolver[zk] = com.twitter.finagle.zookeeper.ZkResolver(com.twitter.finagle.zookeeper.ZkResolver@105edc)
I 1122 10:36:32.165 THREAD1: Resolver[zk2] = com.twitter.finagle.serverset2.Zk2Resolver(com.twitter.finagle.serverset2.Zk2Resolver@b972d7)
I 1122 10:36:32.160 THREAD1: Resolver[fixedinet] = com.twitter.finagle.FixedInetResolver(com.twitter.finagle.FixedInetResolver@1f1cff6)
I 1122 10:36:32.161 THREAD1: Resolver[neg] = com.twitter.finagle.NegResolver$(com.twitter.finagle.NegResolver$@d926d3)
I 1122 10:36:32.162 THREAD1: Resolver[nil] = com.twitter.finagle.NilResolver$(com.twitter.finagle.NilResolver$@1ce27f2)
I 1122 10:36:32.162 THREAD1: Resolver[fail] = com.twitter.finagle.FailResolver$(com.twitter.finagle.FailResolver$@96a4ea)
I 1122 10:36:32.695 THREAD1: serving http admin on /0.0.0.0:9990
I 1122 10:36:32.772 THREAD1: serving io.l5d.thriftNameInterpreter interface on /0.0.0.0:4100
I 1122 10:36:32.802 THREAD1: serving io.l5d.httpController interface on /0.0.0.0:4180


I 1122 10:39:51.767 THREAD22: Drainer is disabled; bypassing


E 1122 10:40:36.490 THREAD19: adminhttp
io.buoyant.k8s.Api$NotFound
	at io.buoyant.k8s.Api$.parse(Api.scala:64)
	at io.buoyant.k8s.ListResource$$anonfun$get$2.apply(resources.scala:136)
	at io.buoyant.k8s.ListResource$$anonfun$get$2.apply(resources.scala:136)
	at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:1092)
	at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:1091)
	at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:107)
	at com.twitter.util.Promise$Transformer.k(Promise.scala:107)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:117)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:98)
	at com.twitter.util.Promise$$anon$1.run(Promise.scala:421)
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:200)
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:158)
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:272)
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:108)
	at com.twitter.util.Promise.runq(Promise.scala:405)
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:801)
	at com.twitter.util.Promise.update(Promise.scala:775)
	at com.twitter.util.Promise.setValue(Promise.scala:751)
	at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:120)
	at com.twitter.finagle.netty3.transport.ChannelTransport.handleUpstream(ChannelTransport.scala:55)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
	at com.twitter.finagle.netty3.channel.ChannelStatsHandler.messageReceived(ChannelStatsHandler.scala:68)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
	at com.twitter.finagle.netty3.channel.ChannelRequestStatsHandler.messageReceived(ChannelRequestStatsHandler.scala:32)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.ProxyThreadFactory$$anonfun$newProxiedRunnable$1$$anon$1.run(ProxyThreadFactory.scala:19)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by klingerf** [comment]
Hey @gianrubio -- really sorry for the delay in responding.

I'm not positive, but based on the stacktrace, it looks like your Kubernetes cluster might not have [ThirdPartyResources](http://kubernetes.io/docs/user-guide/thirdpartyresources/) enabled. The namerd k8s config in this repo uses the ThirdPartyResources API to store dtabs, using namerd's `io.l5d.k8s` storage, described here:

https://linkerd.io/config/0.8.3/namerd/index.html#kubernetes

Can you try turning on ThirdPartyResources in your cluster to see if that fixes it?  If that's not possible, then you could switch the namerd k8s config to use a different type of storage.  If this is just for the purpose of testing, you could use `io.l5d.inMemory` instead, which doesn't require a persistent backend.  If you want to go that route, then you could apply the following change:

```
diff --git a/k8s-daemonset/k8s/namerd.yml b/k8s-daemonset/k8s/namerd.yml
index 36c5ea2..f66ac73 100644
--- a/k8s-daemonset/k8s/namerd.yml
+++ b/k8s-daemonset/k8s/namerd.yml
@@ -15,11 +15,18 @@ data:
       port: 8001
 
     storage:
-      kind: io.l5d.k8s
-      experimental: true
-      host: localhost
-      port: 8001
-      namespace: default
+      kind: io.l5d.inMemory
+      namespaces:
+        external: |
+          /host       => /#/io.l5d.k8s/default/http/hello;
+          /http/*/*/* => /host;
+        incoming: ""
+        outgoing: |
+          /srv        => /#/io.l5d.k8s/default/http;
+          /host       => /srv;
+          /tmp        => /srv;
+          /http/*/*   => /host;
+          /host/world => /srv/world-v1;
 
     interfaces:
     - kind: io.l5d.thriftNameInterpreter
```

And you wouldn't need to separately run the namerctl command to populate the dtab namespaces, since they're already supplied with the config.  Let us know if either of these solutions work for you.  Thanks!

**Comment by klingerf** [comment]
@gianrubio We finally found the underlying cause of this issue, and have fixed it in the linkerd-example master branch. Better late than never. 😉  Thanks for reporting, and feel free to give it a try again, using the instructions here:

https://github.com/BuoyantIO/linkerd-examples/tree/master/k8s-daemonset#daemonsets--namerd--edge-routing
